name: Rustify CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: rustify-linux
        path: target/release/rustify

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: rustify-windows
        path: target\release\rustify.exe

